name: Epic
description: Track a major initiative (contains multiple stories/tasks)
title: "[Epic] "
projects: "Indef Lab"
body:
- type: textarea
  id: EpicSummary
  attributes:
    label: Epic Summary
    description: A brief summary of the epic

- type: textarea
  id: goals
  attributes:
    label: Goals
    description: What does this Epic aim to achieve?
    placeholder: |
      - Goal 1
      - Goal 2

- type: textarea
  id: AcceptanceCriteria
  attributes:
    label: Acceptance Criteria
    description: What are the user stories or characteristics that define done for this Epic?
    placeholder: |
      - AC 1
      - AC 2

- type: textarea
  id: PreRequisites
  attributes:
    label: Pre-Requisite Epics
    description: What Epics must be completed before this Epic can begin?
    placeholder: |
      - [ ] Pre-Req Epic

- type: textarea
  id: Stories
  attributes:
    label: Stories
    description: What are the component stories that make up this Epic?
    placeholder: |
      May be empty if no stories exist currently
      - [ ] Story 1
